package BankAccount;

import iqrahospital.FirstScreen;
import Images.AppIcon;
import iqrahospital.SearchAppoinment;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author shada
 */
public class MyAccount extends javax.swing.JFrame {

    /**
     * Creates new form MyAccount
     */
    int accountNo;

    public MyAccount(int accountNo) {
        initComponents();
        AppIcon.setIcon(this);
        this.accountNo = accountNo;
        updateName();
    }

    public MyAccount() {
        initComponents();
        AppIcon.setIcon(this);
    }

    String naam;
    
    private void updateName() {
        int bal;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");

            // Retrieve the data using the unique ID
            String selectStatement = "SELECT * FROM BankAccount WHERE accountNumber = ?";
            PreparedStatement stmt = conn.prepareStatement(selectStatement);
            stmt.setInt(1, accountNo);
            ResultSet result = stmt.executeQuery();

            // Retrieve the first row of data
            if (result.next()) {
                bal = result.getInt("balance");
                naam = result.getString("AccountTitle");
                String finalBal = String.valueOf(bal);
                LBalance.setText(finalBal + ".00PKR");
                LName.setText("Hi " + naam + ", Welcome Back");

            }

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LBalance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAddAmount = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSendAmount = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IQRA HOSPITAL");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(18, 25, 67));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 6));

        LBalance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        LBalance.setForeground(new java.awt.Color(255, 255, 255));
        LBalance.setText("30000");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ScreensLogo.png"))); // NOI18N
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setAlignmentY(1.0F);

        LName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        LName.setForeground(new java.awt.Color(255, 255, 255));
        LName.setText("Hi NameHere, Welcome Back");
        LName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CURRENT BALANCE");

        btnAddAmount.setBackground(new java.awt.Color(18, 25, 67));
        btnAddAmount.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btnAddAmount.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAddAmount.setText("ADD AMOUNT");
        btnAddAmount.setAlignmentX(0.5F);
        btnAddAmount.setAlignmentY(0.8F);
        btnAddAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAddAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAmountMouseClicked(evt);
            }
        });
        btnAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAmountActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Version 2.0");

        btnSendAmount.setBackground(new java.awt.Color(18, 25, 67));
        btnSendAmount.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btnSendAmount.setForeground(new java.awt.Color(255, 255, 255));
        btnSendAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transaction.png"))); // NOI18N
        btnSendAmount.setText("SEND AMOUNT");
        btnSendAmount.setAlignmentX(0.5F);
        btnSendAmount.setAlignmentY(0.8F);
        btnSendAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnSendAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendAmountActionPerformed(evt);
            }
        });

        btnCard.setBackground(new java.awt.Color(18, 25, 67));
        btnCard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btnCard.setForeground(new java.awt.Color(255, 255, 255));
        btnCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/credit-card-payment.png"))); // NOI18N
        btnCard.setText("VIEW CARD");
        btnCard.setAlignmentX(0.5F);
        btnCard.setAlignmentY(0.8F);
        btnCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(18, 25, 67));
        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setAlignmentX(0.5F);
        btnLogout.setAlignmentY(0.8F);
        btnLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBalance)
                            .addComponent(jLabel8)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(LName))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(LName)
                .addGap(18, 18, 18)
                .addComponent(LBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAmountActionPerformed

    }//GEN-LAST:event_btnAddAmountActionPerformed

    private void btnSendAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendAmountActionPerformed
        try {
            int userAccountNumber = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Enter Account Number: "));
            if (userAccountNumber == accountNo) {
                JOptionPane.showMessageDialog(this, "You Mistakenly Input Your Account Number :) ");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
                String selectStatement = "SELECT * FROM bankAccount WHERE accountNumber = ?";
                PreparedStatement stmt = conn.prepareStatement(selectStatement);
                stmt.setInt(1, userAccountNumber);
                ResultSet result = stmt.executeQuery();

                //Check weather Appointment Number is found in DB
                if (result.next()) {
                    System.out.println("Account found!");
                    SendMoney sm = new SendMoney(userAccountNumber, accountNo, naam);
                    sm.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Account Not Found!");
                }

                conn.close();
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");
        }
    }//GEN-LAST:event_btnSendAmountActionPerformed

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        Card card = new Card(accountNo);
        card.setVisible(true);
    }//GEN-LAST:event_btnCardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        FirstScreen fs = new FirstScreen();
        fs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    String accountTitle;
    double amount;

    public void transaction() {
        // Create a Date object with your date and time.
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.ENGLISH);
        String formattedDate = sdf.format(date);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            String insertStatement = "INSERT INTO transaction (SenderNo, SenderName, ReceiverNo, ReceiverName,Amount, date) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ptst = conn.prepareStatement(insertStatement);

            //Set parameter value where ? in SQL Query
            ptst.setInt(1, accountNo);
            ptst.setString(2, accountTitle);
            ptst.setInt(3, accountNo);
            ptst.setString(4, accountTitle);
            ptst.setDouble(5, amount);
            ptst.setString(6, formattedDate);
            ptst.executeUpdate();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");
        }
    }


    private void btnAddAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAmountMouseClicked
        amount = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Enter your amount: "));
        //DATABASE
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");

            String selectStatement = "SELECT * FROM BankAccount WHERE AccountNumber = ?";
            PreparedStatement stmt = conn.prepareStatement(selectStatement);
            stmt.setInt(1, accountNo);
            ResultSet result = stmt.executeQuery();

            // Retrieve the first row of data
            if (result.next()) {
                accountTitle = result.getString("AccountTitle");
                double Balance = result.getDouble("Balance");
                double FinalBalance = Balance + amount;

                transaction();
                String updateStatement = "UPDATE BankAccount SET balance = ? WHERE AccountNumber = ?";
                PreparedStatement ptst = conn.prepareStatement(updateStatement);

                ptst.setDouble(1, FinalBalance);
                ptst.setInt(2, accountNo);
                ptst.executeUpdate();

                conn.close();
                MyAccount ma = new MyAccount(accountNo);
                ma.setVisible(true);
                dispose();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
        }
    }//GEN-LAST:event_btnAddAmountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBalance;
    private javax.swing.JLabel LName;
    private javax.swing.JButton btnAddAmount;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSendAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
