/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminPanel;

import iqrahospital.Payment;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author shada
 */
public class ServePatients extends javax.swing.JFrame {

    private Queue<String> patientQueue;
    //private String currentPatient;
    private String mrNumber;
    String selectedDoctor;
    String selectedCategory;
    String selectedTime;

    /**
     * Creates new form ServePatients
     */
    public ServePatients() {
        initComponents();
    }

    public ServePatients(String selectedDoctor, String selectedCategory, String selectedTime) {
        initComponents();
        this.selectedDoctor = selectedDoctor;
        this.selectedCategory = selectedCategory;
        this.selectedTime = selectedTime;
        patientQueue = new LinkedList<>();
        nextPatientButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextPatientButton = new javax.swing.JButton();
        startCheckButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        servingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IRQA HOSPITAL");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(18, 25, 67));

        nextPatientButton.setBackground(new java.awt.Color(18, 25, 67));
        nextPatientButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nextPatientButton.setForeground(new java.awt.Color(255, 255, 255));
        nextPatientButton.setText("NEXT PATIENT");
        nextPatientButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        nextPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPatientButtonActionPerformed(evt);
            }
        });

        startCheckButton.setBackground(new java.awt.Color(18, 25, 67));
        startCheckButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        startCheckButton.setForeground(new java.awt.Color(255, 255, 255));
        startCheckButton.setText("START CHECKUP");
        startCheckButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        startCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCheckButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ScreensLogo.png"))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 25, 67), 1, true));

        servingLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        servingLabel.setForeground(new java.awt.Color(18, 25, 67));
        servingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servingLabel.setText("NO PATIENT RECORD");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CURRENTLY SERVING:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addComponent(servingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servingLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow (2).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(startCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(95, 95, 95)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void enqueue(String patientMRNumber) {
        patientQueue.add(patientMRNumber);
    }

    public String dequeue() {
        if (!isEmpty()) {
            mrNumber = patientQueue.poll();
            return mrNumber;
        }
        return null;
    }

    public boolean isEmpty() {
        return patientQueue.isEmpty();
    }

    public int count() {
        return patientQueue.size();
    }

    public String getName(String mrNumber) {
        String patientName = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            String selectStatement = "SELECT * FROM patientdata WHERE MrNumber = ?";
            PreparedStatement stmt = conn.prepareStatement(selectStatement);
            stmt.setString(1, mrNumber);
            ResultSet result = stmt.executeQuery();

            while (result.next()) {
                patientName = result.getString("FirstName");
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return patientName;
    }

    public void updateStatus(String mrNumber) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            String updateStatement = "UPDATE patientdata SET patientStatus = ? WHERE mrNumber = ?";
            PreparedStatement ptst = conn.prepareStatement(updateStatement);
            ptst.setString(1, "Checked");
            ptst.setString(2, mrNumber);
            ptst.executeUpdate();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");
        }
    }

    public void loadPatientsFromDatabase(String status) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            String selectStatement = "SELECT * FROM patientdata WHERE Doctor = ? AND speciality = ? AND timeSlot = ?  AND  patientStatus = ? ORDER BY MRNumber ASC";
            PreparedStatement stmt = conn.prepareStatement(selectStatement);
            stmt.setString(1, selectedDoctor);
            stmt.setString(2, selectedCategory);
            stmt.setString(3, selectedTime);
            stmt.setString(4, status);
            ResultSet result = stmt.executeQuery();

            while (result.next()) {
                String mrNum = result.getString("mrNumber");
                enqueue(mrNum); // Enqueue MR number
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void nextPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPatientButtonActionPerformed
        if (!patientQueue.isEmpty()) {
            mrNumber = patientQueue.poll();
            updateStatus(mrNumber); // Update status using the current MR number
            dequeue();
            String patientName = getName(mrNumber);
            String displayText = "Now serving: " + patientName + " (MR No: " + mrNumber + ")";
            servingLabel.setText(displayText);
        } else {
            servingLabel.setText("No patient in queue");
            nextPatientButton.setVisible(false);
        }
    }//GEN-LAST:event_nextPatientButtonActionPerformed

    private void startCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCheckButtonActionPerformed
        loadPatientsFromDatabase("waiting");
        if (!patientQueue.isEmpty()) {
            mrNumber = patientQueue.poll(); // Set the current MR number
            updateStatus(mrNumber); // Update status using the current MR number
            String patientName = getName(mrNumber);
            String displayText = "Now serving: " + patientName + " (MR No: " + mrNumber + ")";
            servingLabel.setText(displayText);

            startCheckButton.setVisible(false);
            nextPatientButton.setVisible(true);
        } else {
            servingLabel.setText("No patient in queue");
        }
    }//GEN-LAST:event_startCheckButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Dashboard da = new Dashboard();
       da.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServePatients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServePatients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServePatients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServePatients.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServePatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextPatientButton;
    private javax.swing.JLabel servingLabel;
    private javax.swing.JButton startCheckButton;
    // End of variables declaration//GEN-END:variables
}
